<?php

namespace AppBundle\Repository;

/**
 * AthletesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AthletesRepository extends \Doctrine\ORM\EntityRepository
{
}
