<?php

namespace AppBundle\Repository;

/**
 * EpreuvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuvesRepository extends \Doctrine\ORM\EntityRepository
{
}
