

# ---------------------> LOGIN/NEW USER <---------------------

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

registration:
    path:     /registration/confirmed
    defaults: { _controller: AppBundle:Registration:register }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_logout:
    path:    /user/logout
    defaults: { _controller: AppBundle:Security:logout }

home:
    path:     /home
    defaults: { _controller: AppBundle:Default:home }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

epreuves:
    path:     /epreuves/{idepreuves}
    defaults: { _controller: AppBundle:Epreuves:epreuves }

show:
    path:     /show
    defaults: { _controller: AppBundle:Default:show }







